/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppSectionsRouteImport } from './routes/_app/sections'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppOrderSuccessRouteImport } from './routes/_app/order-success'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account.index'
import { Route as AppStoreWholesaleRouteImport } from './routes/_app/store.wholesale'
import { Route as AppStoreSupermarketRouteImport } from './routes/_app/store.supermarket'
import { Route as AppStoreSubscriptionRouteImport } from './routes/_app/store.subscription'
import { Route as AppStoreRecipesRouteImport } from './routes/_app/store.recipes'
import { Route as AppStoreProduceRouteImport } from './routes/_app/store.produce'
import { Route as AppStorePharmacyRouteImport } from './routes/_app/store.pharmacy'
import { Route as AppStoreLibraryRouteImport } from './routes/_app/store.library'
import { Route as AppStoreKitchenRouteImport } from './routes/_app/store.kitchen'
import { Route as AppStoreHomeRouteImport } from './routes/_app/store.home'
import { Route as AppStoreDairyRouteImport } from './routes/_app/store.dairy'
import { Route as AppProductProductIdRouteImport } from './routes/_app/product.$productId'
import { Route as AppAccountSettingsRouteImport } from './routes/_app/account.settings'
import { Route as AppAccountProfileRouteImport } from './routes/_app/account.profile'
import { Route as AppAccountPaymentsRouteImport } from './routes/_app/account.payments'
import { Route as AppAccountOrdersRouteImport } from './routes/_app/account.orders'
import { Route as AppAccountNotificationsRouteImport } from './routes/_app/account.notifications'
import { Route as AppAccountHelpRouteImport } from './routes/_app/account.help'
import { Route as AppAccountFavoritesRouteImport } from './routes/_app/account.favorites'
import { Route as AppAccountAddressesRouteImport } from './routes/_app/account.addresses'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionsRoute = AppSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderSuccessRoute = AppOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppStoreWholesaleRoute = AppStoreWholesaleRouteImport.update({
  id: '/store/wholesale',
  path: '/store/wholesale',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreSupermarketRoute = AppStoreSupermarketRouteImport.update({
  id: '/store/supermarket',
  path: '/store/supermarket',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreSubscriptionRoute = AppStoreSubscriptionRouteImport.update({
  id: '/store/subscription',
  path: '/store/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRecipesRoute = AppStoreRecipesRouteImport.update({
  id: '/store/recipes',
  path: '/store/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreProduceRoute = AppStoreProduceRouteImport.update({
  id: '/store/produce',
  path: '/store/produce',
  getParentRoute: () => AppRoute,
} as any)
const AppStorePharmacyRoute = AppStorePharmacyRouteImport.update({
  id: '/store/pharmacy',
  path: '/store/pharmacy',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreLibraryRoute = AppStoreLibraryRouteImport.update({
  id: '/store/library',
  path: '/store/library',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreKitchenRoute = AppStoreKitchenRouteImport.update({
  id: '/store/kitchen',
  path: '/store/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreHomeRoute = AppStoreHomeRouteImport.update({
  id: '/store/home',
  path: '/store/home',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreDairyRoute = AppStoreDairyRouteImport.update({
  id: '/store/dairy',
  path: '/store/dairy',
  getParentRoute: () => AppRoute,
} as any)
const AppProductProductIdRoute = AppProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSettingsRoute = AppAccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountPaymentsRoute = AppAccountPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountOrdersRoute = AppAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountNotificationsRoute = AppAccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountHelpRoute = AppAccountHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountFavoritesRoute = AppAccountFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountAddressesRoute = AppAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppAccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRouteWithChildren
  '/cart': typeof AppCartRoute
  '/offers': typeof AppOffersRoute
  '/order-success': typeof AppOrderSuccessRoute
  '/search': typeof AppSearchRoute
  '/sections': typeof AppSectionsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/': typeof AdminIndexRoute
  '/account/addresses': typeof AppAccountAddressesRoute
  '/account/favorites': typeof AppAccountFavoritesRoute
  '/account/help': typeof AppAccountHelpRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/orders': typeof AppAccountOrdersRoute
  '/account/payments': typeof AppAccountPaymentsRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/product/$productId': typeof AppProductProductIdRoute
  '/store/dairy': typeof AppStoreDairyRoute
  '/store/home': typeof AppStoreHomeRoute
  '/store/kitchen': typeof AppStoreKitchenRoute
  '/store/library': typeof AppStoreLibraryRoute
  '/store/pharmacy': typeof AppStorePharmacyRoute
  '/store/produce': typeof AppStoreProduceRoute
  '/store/recipes': typeof AppStoreRecipesRoute
  '/store/subscription': typeof AppStoreSubscriptionRoute
  '/store/supermarket': typeof AppStoreSupermarketRoute
  '/store/wholesale': typeof AppStoreWholesaleRoute
  '/account/': typeof AppAccountIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cart': typeof AppCartRoute
  '/offers': typeof AppOffersRoute
  '/order-success': typeof AppOrderSuccessRoute
  '/search': typeof AppSearchRoute
  '/sections': typeof AppSectionsRoute
  '/wallet': typeof AppWalletRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/addresses': typeof AppAccountAddressesRoute
  '/account/favorites': typeof AppAccountFavoritesRoute
  '/account/help': typeof AppAccountHelpRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/orders': typeof AppAccountOrdersRoute
  '/account/payments': typeof AppAccountPaymentsRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/account/settings': typeof AppAccountSettingsRoute
  '/product/$productId': typeof AppProductProductIdRoute
  '/store/dairy': typeof AppStoreDairyRoute
  '/store/home': typeof AppStoreHomeRoute
  '/store/kitchen': typeof AppStoreKitchenRoute
  '/store/library': typeof AppStoreLibraryRoute
  '/store/pharmacy': typeof AppStorePharmacyRoute
  '/store/produce': typeof AppStoreProduceRoute
  '/store/recipes': typeof AppStoreRecipesRoute
  '/store/subscription': typeof AppStoreSubscriptionRoute
  '/store/supermarket': typeof AppStoreSupermarketRoute
  '/store/wholesale': typeof AppStoreWholesaleRoute
  '/account': typeof AppAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/cart': typeof AppCartRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/order-success': typeof AppOrderSuccessRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/sections': typeof AppSectionsRoute
  '/_app/wallet': typeof AppWalletRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/account/addresses': typeof AppAccountAddressesRoute
  '/_app/account/favorites': typeof AppAccountFavoritesRoute
  '/_app/account/help': typeof AppAccountHelpRoute
  '/_app/account/notifications': typeof AppAccountNotificationsRoute
  '/_app/account/orders': typeof AppAccountOrdersRoute
  '/_app/account/payments': typeof AppAccountPaymentsRoute
  '/_app/account/profile': typeof AppAccountProfileRoute
  '/_app/account/settings': typeof AppAccountSettingsRoute
  '/_app/product/$productId': typeof AppProductProductIdRoute
  '/_app/store/dairy': typeof AppStoreDairyRoute
  '/_app/store/home': typeof AppStoreHomeRoute
  '/_app/store/kitchen': typeof AppStoreKitchenRoute
  '/_app/store/library': typeof AppStoreLibraryRoute
  '/_app/store/pharmacy': typeof AppStorePharmacyRoute
  '/_app/store/produce': typeof AppStoreProduceRoute
  '/_app/store/recipes': typeof AppStoreRecipesRoute
  '/_app/store/subscription': typeof AppStoreSubscriptionRoute
  '/_app/store/supermarket': typeof AppStoreSupermarketRoute
  '/_app/store/wholesale': typeof AppStoreWholesaleRoute
  '/_app/account/': typeof AppAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/account'
    | '/cart'
    | '/offers'
    | '/order-success'
    | '/search'
    | '/sections'
    | '/wallet'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/wallets'
    | '/admin/'
    | '/account/addresses'
    | '/account/favorites'
    | '/account/help'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/settings'
    | '/product/$productId'
    | '/store/dairy'
    | '/store/home'
    | '/store/kitchen'
    | '/store/library'
    | '/store/pharmacy'
    | '/store/produce'
    | '/store/recipes'
    | '/store/subscription'
    | '/store/supermarket'
    | '/store/wholesale'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cart'
    | '/offers'
    | '/order-success'
    | '/search'
    | '/sections'
    | '/wallet'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/wallets'
    | '/'
    | '/admin'
    | '/account/addresses'
    | '/account/favorites'
    | '/account/help'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/profile'
    | '/account/settings'
    | '/product/$productId'
    | '/store/dairy'
    | '/store/home'
    | '/store/kitchen'
    | '/store/library'
    | '/store/pharmacy'
    | '/store/produce'
    | '/store/recipes'
    | '/store/subscription'
    | '/store/supermarket'
    | '/store/wholesale'
    | '/account'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/account'
    | '/_app/cart'
    | '/_app/offers'
    | '/_app/order-success'
    | '/_app/search'
    | '/_app/sections'
    | '/_app/wallet'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/wallets'
    | '/_app/'
    | '/admin/'
    | '/_app/account/addresses'
    | '/_app/account/favorites'
    | '/_app/account/help'
    | '/_app/account/notifications'
    | '/_app/account/orders'
    | '/_app/account/payments'
    | '/_app/account/profile'
    | '/_app/account/settings'
    | '/_app/product/$productId'
    | '/_app/store/dairy'
    | '/_app/store/home'
    | '/_app/store/kitchen'
    | '/_app/store/library'
    | '/_app/store/pharmacy'
    | '/_app/store/produce'
    | '/_app/store/recipes'
    | '/_app/store/subscription'
    | '/_app/store/supermarket'
    | '/_app/store/wholesale'
    | '/_app/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sections': {
      id: '/_app/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AppSectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order-success': {
      id: '/_app/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof AppOrderSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/store/wholesale': {
      id: '/_app/store/wholesale'
      path: '/store/wholesale'
      fullPath: '/store/wholesale'
      preLoaderRoute: typeof AppStoreWholesaleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/supermarket': {
      id: '/_app/store/supermarket'
      path: '/store/supermarket'
      fullPath: '/store/supermarket'
      preLoaderRoute: typeof AppStoreSupermarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/subscription': {
      id: '/_app/store/subscription'
      path: '/store/subscription'
      fullPath: '/store/subscription'
      preLoaderRoute: typeof AppStoreSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/recipes': {
      id: '/_app/store/recipes'
      path: '/store/recipes'
      fullPath: '/store/recipes'
      preLoaderRoute: typeof AppStoreRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/produce': {
      id: '/_app/store/produce'
      path: '/store/produce'
      fullPath: '/store/produce'
      preLoaderRoute: typeof AppStoreProduceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/pharmacy': {
      id: '/_app/store/pharmacy'
      path: '/store/pharmacy'
      fullPath: '/store/pharmacy'
      preLoaderRoute: typeof AppStorePharmacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/library': {
      id: '/_app/store/library'
      path: '/store/library'
      fullPath: '/store/library'
      preLoaderRoute: typeof AppStoreLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/kitchen': {
      id: '/_app/store/kitchen'
      path: '/store/kitchen'
      fullPath: '/store/kitchen'
      preLoaderRoute: typeof AppStoreKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/home': {
      id: '/_app/store/home'
      path: '/store/home'
      fullPath: '/store/home'
      preLoaderRoute: typeof AppStoreHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store/dairy': {
      id: '/_app/store/dairy'
      path: '/store/dairy'
      fullPath: '/store/dairy'
      preLoaderRoute: typeof AppStoreDairyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product/$productId': {
      id: '/_app/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof AppProductProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/settings': {
      id: '/_app/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppAccountSettingsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/profile': {
      id: '/_app/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/payments': {
      id: '/_app/account/payments'
      path: '/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AppAccountPaymentsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/orders': {
      id: '/_app/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AppAccountOrdersRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/notifications': {
      id: '/_app/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AppAccountNotificationsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/help': {
      id: '/_app/account/help'
      path: '/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof AppAccountHelpRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/favorites': {
      id: '/_app/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AppAccountFavoritesRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/addresses': {
      id: '/_app/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AppAccountAddressesRouteImport
      parentRoute: typeof AppAccountRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountAddressesRoute: typeof AppAccountAddressesRoute
  AppAccountFavoritesRoute: typeof AppAccountFavoritesRoute
  AppAccountHelpRoute: typeof AppAccountHelpRoute
  AppAccountNotificationsRoute: typeof AppAccountNotificationsRoute
  AppAccountOrdersRoute: typeof AppAccountOrdersRoute
  AppAccountPaymentsRoute: typeof AppAccountPaymentsRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountSettingsRoute: typeof AppAccountSettingsRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountAddressesRoute: AppAccountAddressesRoute,
  AppAccountFavoritesRoute: AppAccountFavoritesRoute,
  AppAccountHelpRoute: AppAccountHelpRoute,
  AppAccountNotificationsRoute: AppAccountNotificationsRoute,
  AppAccountOrdersRoute: AppAccountOrdersRoute,
  AppAccountPaymentsRoute: AppAccountPaymentsRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountSettingsRoute: AppAccountSettingsRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppCartRoute: typeof AppCartRoute
  AppOffersRoute: typeof AppOffersRoute
  AppOrderSuccessRoute: typeof AppOrderSuccessRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSectionsRoute: typeof AppSectionsRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProductProductIdRoute: typeof AppProductProductIdRoute
  AppStoreDairyRoute: typeof AppStoreDairyRoute
  AppStoreHomeRoute: typeof AppStoreHomeRoute
  AppStoreKitchenRoute: typeof AppStoreKitchenRoute
  AppStoreLibraryRoute: typeof AppStoreLibraryRoute
  AppStorePharmacyRoute: typeof AppStorePharmacyRoute
  AppStoreProduceRoute: typeof AppStoreProduceRoute
  AppStoreRecipesRoute: typeof AppStoreRecipesRoute
  AppStoreSubscriptionRoute: typeof AppStoreSubscriptionRoute
  AppStoreSupermarketRoute: typeof AppStoreSupermarketRoute
  AppStoreWholesaleRoute: typeof AppStoreWholesaleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppCartRoute: AppCartRoute,
  AppOffersRoute: AppOffersRoute,
  AppOrderSuccessRoute: AppOrderSuccessRoute,
  AppSearchRoute: AppSearchRoute,
  AppSectionsRoute: AppSectionsRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
  AppProductProductIdRoute: AppProductProductIdRoute,
  AppStoreDairyRoute: AppStoreDairyRoute,
  AppStoreHomeRoute: AppStoreHomeRoute,
  AppStoreKitchenRoute: AppStoreKitchenRoute,
  AppStoreLibraryRoute: AppStoreLibraryRoute,
  AppStorePharmacyRoute: AppStorePharmacyRoute,
  AppStoreProduceRoute: AppStoreProduceRoute,
  AppStoreRecipesRoute: AppStoreRecipesRoute,
  AppStoreSubscriptionRoute: AppStoreSubscriptionRoute,
  AppStoreSupermarketRoute: AppStoreSupermarketRoute,
  AppStoreWholesaleRoute: AppStoreWholesaleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
